#' DayTypes Dataset
#'
#' A dataset indicating different types of days used in the effort analysis.
#'
#' This dataset categorizes days as "Weekday", "Weekend", or "Holiday", which are
#' used for modeling effort variations in the DP2R package.
#'
#' @format A data frame with 3 columns:
#' \describe{
#'   \item{Date}{Date in "YYYY-MM-DD" format.}
#'   \item{DayType}{A factor with levels: "Weekday", "Weekend", "Holiday".}
#'   \item{Description}{A short description of the day type.}
#' }
#' @usage data(DayTypes)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(DayTypes)
#' head(DayTypes)
"DayTypes"

# ----------------------------------------------------------------------
#' Pred_vars Dataset
#'
#' A data frame summarizing frequency of variable categories for efficient model predictions used in the effort analysis.
#'
#' This dataset categorizes daytypes, weather, hour of unobserved counts to extrapolate effort estimates to a full season.Used within EffortEst function.
#'
#' @format A data frame with 6 columns:
#' \describe{
#'   \item{year}{year in numeric format.}
#'   \item{month}{month in numeric format.}
#'   \item{daytype}{A factor with levels: "WD", "WE", "LWE".}
#'   \item{ndays}{An integer describing the number of days for that daytype category in the given month}
#'   \item{hour}{hour in character format}
#'   \item{weather_code}{A character string describing the weather catgory as POOR, FAIR or GOOD.}
#' }
#' @usage data(Pred_vars)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(Pred_vars)
#' head(Pred_vars)
"Pred_vars"

# ----------------------------------------------------------------------
#' DP2R_Effort_Model
#'
#' A `glmer` model object for predicting effort based on day types and other variables.
#'
#' This object contains a generalized linear mixed-effects model (GLMM) fitted using the
#' `lme4::glmer()` function. It is stored in the package as a compressed .qs2 file, but is not exported. You can load this object into your environment using the `qs2::qs_read()` function.
#'
#' @format An object of class `glmerMod`, loaded into the environment as `fit`.
#' @usage qs2::qs_read("data/DP2R_Effort_Model.qs2")
#' @source Generated by fitting a GLMM using the `lme4` package.
#'
#' @examples
#' # To see model summary:
#' qs2::qs_read("data/DP2R_Effort_Model.qs2")
#'
#' # To load the model and use the mode, assign to an object:
#' fit <- qs2::qs_read("data/DP2R_Effort_Model.qs2")


# ----------------------------------------------------------------------
#' DP2R_Ice_Model
#'
#' A `glmer` model object for predicting effort based on day types and other variables.
#'
#' This object contains a generalized linear mixed-effects model (GLMM) fitted using the
#' `lme4::glmer()` function. It is stored in the package as a compressed .qs2 file, but is not exported. You can load this object into your environment using the `qs2::qs_read()` function.
#'
#' @format An object of class `glmerMod`, loaded into the environment as `fit`.
#' @usage qs2::qs_read("data/DP2R_Ice_Model.qs2")
#' @source Generated by fitting a GLMM using the `lme4` package.
#'
#' @examples
#' # To see a model summary:
#' qs2::qs_read("data/DP2R_Ice_Model.qs2")
#'
#' # To load the model and use the mode, assign to an object:
#' fit <- qs2::qs_read("data/DP2R_Ice_Model.qs2")


#' # ----------------------------------------------------------------------
#' shinydata Dataset
#'
#' A data frame summarizing effort estimates for lakes for each year/fishing season assessed, which underlies the Shiny application used by provincial biologists. Open water fishing season is standardized from May 1st to October 31st.
#'
#'
#' @format A data frame with 18 columns:
#' \describe{
#'   \item{region}{managment region, character}
#'   \item{WBID}{Waterbody Identifie, character}
#'   \item{gazetted_name}{Gazetted waterbody name}
#'   \item{view_location_name}{A unique name given to a specific viewpoint of a lake by camera or ground}
#'   \item{year}{hour in character format}
#'   \item{method}{A character string describing the method used to count effort CAM, AIR, GRD}
#'   \item{N}{The number of observations for the specified year/fishing season a lake has been assessed, integer}
#'   \item{spv_obs}{The total number of single person vessels observed angling in year, integer}
#'   \item{boats_obs}{The total number of angling boats observed in year, integer}
#'   \item{shore_obs}{The total number of shore anglers observed in year, integer}
#'   \item{spv_AD}{The estimated total angler days from single person vessels in fishing season, integer}
#'   \item{boats_AD}{The estimated total angler days from angling boats in fishing season, integer}
#'   \item{shore_AD}{The estimated total angler days from shore anglers in fishing season, integer}
#'   \item{Angler_days}{The estimated total angler days in fishing season. WIll be NA for camera counts without verified Cam_Exp, integer}
#'   \item{Angler_days_p_ha}{The estimated total angler days per hectare of lake area in fishing season, numeric}
#'   \item{area_ha}{The lake surface area in hectares, numeric}
#'   \item{Cam_Exp}{The expansion factor used to expand the estimated effort seen from the view_locaiton_name to the entire lake, numeric}
#'   \item{Exp_N}{The numerb of verification counts used to estimate the Cam_Exp, numeric}
#'
#' }
#' @usage data(shinydata)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(shinydata)
#' head(shinydata)
"shinydata"

#' # ----------------------------------------------------------------------
#' lakesum Dataset
#'
#' A data frame summarizing effort estimates for lakes over all years assessed, which underlies the Shiny application used by provincial biologists.
#'
#'
#' @format A data frame with 10 columns:
#' \describe{
#'   \item{region}{managment region, character}
#'   \item{WBID}{Waterbody Identifie, character}
#'   \item{gazetted_name}{Gazetted waterbody name}
#'   \item{N_years}{the number of different calendar years with effort estimates, integer}
#'   \item{min_year}{the earliest year with effort estimates, integer}
#'   \item{max_year}{the nmost recent year effort estimates, integer}
#'   \item{Methods}{A character string describing the different methods used to count effort CAM, AIR, GRD}
#'   \item{mean_AD}{The average estimated total angler days across years assessed, numeric}
#'   \item{marker_size}{A value equal to mean_AD for plotting}
#'   \item{AD_percentile}{The percentile rank, province wide, of the average anglers days estiamted for a given lake.}
#'   \item{lake_latitude}{coordinate of lake, numeric}
#'   \item{lake_longitude}{coordinate of lake, numeric}
#' }
#' @usage data(lakesum)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(lakesum)
#' head(lakesum)
"lakesum"

