#' DayTypes Dataset
#'
#' A dataset indicating different types of days used in the effort analysis.
#'
#' This dataset categorizes days as "Weekday", "Weekend", or "Holiday", which are
#' used for modeling effort variations in the DP2R package.
#'
#' @format A data frame with 3 columns:
#' \describe{
#'   \item{Date}{Date in "YYYY-MM-DD" format.}
#'   \item{DayType}{A factor with levels: "Weekday", "Weekend", "Holiday".}
#'   \item{Description}{A short description of the day type.}
#' }
#' @usage data(DayTypes)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(DayTypes)
#' head(DayTypes)
"DayTypes"

# ----------------------------------------------------------------------
#' Pred_vars Dataset
#'
#' A data frame summarizing frequency of variable categories for efficient model predictions used in the effort analysis.
#'
#' This dataset categorizes daytypes, weather, hour of unobserved counts to extrapolate effort estimates to a full season.Used within EffortEst function.
#'
#' @format A data frame with 6 columns:
#' \describe{
#'   \item{year}{year in numeric format.}
#'   \item{month}{month in numeric format.}
#'   \item{daytype}{A factor with levels: "WD", "WE", "LWE".}
#'   \item{ndays}{An integer describing the number of days for that daytype category in the given month}
#'   \item{hour}{hour in character format}
#'   \item{weather_code}{A character string describing the weather catgory as POOR, FAIR or GOOD.}
#' }
#' @usage data(Pred_vars)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(Pred_vars)
#' head(Pred_vars)
"Pred_vars"

# ----------------------------------------------------------------------
#' DP2R_Effort_Model
#'
#' A `glmer` model object for predicting effort based on day types and other variables.
#'
#' This object contains a generalized linear mixed-effects model (GLMM) fitted using the
#' `lme4::glmer()` function. It is stored in the package but is not exported. You can
#' load this object into your environment using the `data()` function or the `load()` function.
#'
#' @format An object of class `glmerMod`, loaded into the environment as `fit`.
#' @usage data("DP2R_Effort_Model", package = "DP2R")
#'        load("data/DP2R_Effort_Model.rda")
#' @source Generated by fitting a GLMM using the `lme4` package.
#'
#' @examples
#' # To load the model, you can use:
#' data("DP2R_Effort_Model", package = "DP2R")
#'
#' # After loading, you can use the model as follows:
#' summary(fit)
"fit"


