#' DayTypes Dataset
#'
#' A dataset indicating different types of days used in the effort analysis.
#'
#' This dataset categorizes days as "Weekday", "Weekend", or "Holiday", which are
#' used for modeling effort variations in the DP2R package.
#'
#' @format A data frame with 3 columns:
#' \describe{
#'   \item{Date}{Date in "YYYY-MM-DD" format.}
#'   \item{DayType}{A factor with levels: "Weekday", "Weekend", "Holiday".}
#'   \item{Description}{A short description of the day type.}
#' }
#' @usage data(DayTypes)
#' @source Generated internally for the DP2R package.
#'
#' @examples
#' data(DayTypes)
#' head(DayTypes)
"DayTypes"

# ----------------------------------------------------------------------

#' DP2R_Effort_Model
#'
#' A `glmer` model object for predicting effort based on day types and other variables.
#'
#' This object contains a generalized linear mixed-effects model (GLMM) fitted using the
#' `lme4::glmer()` function. It is stored in the package but is not exported. You can
#' load this object into your environment using the `data()` function or the `load()` function.
#'
#' @format An object of class `glmerMod`, loaded into the environment as `fit`.
#' @usage data("DP2R_Effort_Model", package = "DP2R")
#'        load("data/DP2R_Effort_Model.rda")
#' @source Generated by fitting a GLMM using the `lme4` package.
#'
#' @examples
#' # To load the model, you can use:
#' data("DP2R_Effort_Model", package = "DP2R")
#'
#' # After loading, you can use the model as follows:
#' summary(fit)
"fit"


